In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_csv("train.txt",sep=';', header = None,names=['text','emotion'])

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:
unique_emotions=df['emotion'].unique()
emotion_nums={}
i=0
for emo in unique_emotions:
  emotion_nums[emo]=i
  i+=1
df['emotion']=df['emotion'].map(emotion_nums)

In [ ]:
df.sample(5)

                                                    text  emotion
15739           i feel dirty disgusting and contaminated        0
14710  i know what happened might still feel real fee...        1
550    i was still feeling strong but i missed a coup...        5
6808   i often feel bothered by it by my inability to...        1
1708   i just feel that the roster looks messy with c...        0

In [ ]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [ ]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [ ]:
df['text']=df['text'].apply(remove_punc)

In [ ]:
def remove_numbers(txt):
  new= ""
  for i in txt:
    if not i.isdigit():
      new+=1
    return new
  df['text']=df['text'].apply(remove_numbers)

In [ ]:
import nltk

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
print(word_tokenize)

<function word_tokenize at 0x7e01dd3f5260>

In [ ]:

stop_words = set(stopwords.words('english'))

def remove(txt):
    words = word_tokenize(txt)

    cleaned = []

    for i in words:
        if i not in stop_words:
            cleaned.append(i)

    return cleaned

In [ ]:
df['text'] = df['text'].apply(remove)

In [ ]:
df.loc[1]['text']

['go',
 'feeling',
 'hopeless',
 'damned',
 'hopeful',
 'around',
 'someone',
 'cares',
 'awake']